module.exports = {
  SET_BPM: 'SET_BPM',
  SET_TEMPO_CHANGE_INTERVAL: 'SET_CHANGE_INTERVAL',
  SET_BPM_DELTA: 'SET_BPM_DELTA',
  INCREMENT_BEAT: 'INCREMENT_BEAT',
  RESET_BEAT: 'RESET_BEAT',
  TOGGLE_PLAY: 'TOGGLE_PLAY',
  SET_PLAY: 'SET_PLAY'
}
