module.exports = {
  // metronome
  SET_BPM: 'SET_BPM',
  SET_TEMPO_CHANGE_INTERVAL: 'SET_CHANGE_INTERVAL',
  SET_BPM_DELTA: 'SET_BPM_DELTA',
  INCREMENT_BEAT: 'INCREMENT_BEAT',
  RESET_BEAT: 'RESET_BEAT',
  TOGGLE_PLAY: 'TOGGLE_PLAY',
  SET_PLAY: 'SET_PLAY',

  // search
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SET_SPIRIT_ANIMAL_SRC: 'SET_SPIRIT_ANIMAL_SRC',
  INCREMENT_SEARCH_RESULTS_PAGE: 'INCREMENT_SEARCH_RESULTS_PAGE',
  DECREMENT_SEARCH_RESULTS_PAGE: 'DECREMENT_SEARCH_RESULTS_PAGE',
  RESET_SEARCH_RESULTS_PAGE: 'RESET_SEARCH_RESULTS_PAGE',
  APPEND_SEARCH_RESULTS: 'APPEND_SEARCH_RESULTS',
  SET_SEARCH_LOADING: 'SET_SEARCH_LOADING'
}
